-- MySQL Script generated by MySQL Workbench
-- Thu 01 Jan 2026 04:48:44 PM EAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema maiduka25db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema maiduka25db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maiduka25db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `maiduka25db` ;

-- -----------------------------------------------------
-- Table `maiduka25db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`users` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `phone_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `is_phone_login_enabled` TINYINT(1) NOT NULL DEFAULT '0',
  `password` VARCHAR(255) NOT NULL,
  `two_factor_secret` TEXT NULL DEFAULT NULL,
  `two_factor_recovery_codes` TEXT NULL DEFAULT NULL,
  `two_factor_confirmed_at` TIMESTAMP NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE,
  UNIQUE INDEX `users_phone_unique` (`phone` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`shops` (
  `id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `business_type` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(20) NULL DEFAULT NULL,
  `address` VARCHAR(1000) NOT NULL,
  `agent_code` VARCHAR(255) NULL DEFAULT NULL,
  `currency` VARCHAR(255) NOT NULL,
  `image_url` VARCHAR(2048) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `shops_agent_code_unique` (`agent_code` ASC) VISIBLE,
  INDEX `shops_owner_id_is_active_index` (`owner_id` ASC, `is_active` ASC) VISIBLE,
  INDEX `shops_agent_code_index` (`agent_code` ASC) VISIBLE,
  CONSTRAINT `shops_owner_id_foreign`
    FOREIGN KEY (`owner_id`)
    REFERENCES `maiduka25db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`active_shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`active_shops` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `selected_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `active_shops_user_id_unique` (`user_id` ASC) VISIBLE,
  INDEX `active_shops_shop_id_foreign` (`shop_id` ASC) VISIBLE,
  CONSTRAINT `active_shops_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `active_shops_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `maiduka25db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`blocked_shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`blocked_shops` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `blocked_shop_id` CHAR(36) NOT NULL,
  `blocked_by` CHAR(36) NOT NULL,
  `reason` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `blocked_shops_shop_id_blocked_shop_id_unique` (`shop_id` ASC, `blocked_shop_id` ASC) VISIBLE,
  INDEX `blocked_shops_blocked_shop_id_foreign` (`blocked_shop_id` ASC) VISIBLE,
  INDEX `blocked_shops_blocked_by_foreign` (`blocked_by` ASC) VISIBLE,
  INDEX `blocked_shops_shop_id_index` (`shop_id` ASC) VISIBLE,
  CONSTRAINT `blocked_shops_blocked_by_foreign`
    FOREIGN KEY (`blocked_by`)
    REFERENCES `maiduka25db`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `blocked_shops_blocked_shop_id_foreign`
    FOREIGN KEY (`blocked_shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `blocked_shops_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`categories` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`conversations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`conversations` (
  `id` CHAR(36) NOT NULL,
  `shop_one_id` CHAR(36) NOT NULL,
  `shop_two_id` CHAR(36) NOT NULL,
  `last_message` TEXT NULL DEFAULT NULL,
  `last_message_by` CHAR(36) NULL DEFAULT NULL,
  `last_message_at` TIMESTAMP NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `is_archived_by_shop_one` TINYINT(1) NOT NULL DEFAULT '0',
  `is_archived_by_shop_two` TINYINT(1) NOT NULL DEFAULT '0',
  `metadata` JSON NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `conversations_shop_one_id_shop_two_id_unique` (`shop_one_id` ASC, `shop_two_id` ASC) VISIBLE,
  INDEX `conversations_last_message_by_foreign` (`last_message_by` ASC) VISIBLE,
  INDEX `conversations_shop_one_id_is_active_index` (`shop_one_id` ASC, `is_active` ASC) VISIBLE,
  INDEX `conversations_shop_two_id_is_active_index` (`shop_two_id` ASC, `is_active` ASC) VISIBLE,
  INDEX `conversations_last_message_at_index` (`last_message_at` ASC) VISIBLE,
  CONSTRAINT `conversations_last_message_by_foreign`
    FOREIGN KEY (`last_message_by`)
    REFERENCES `maiduka25db`.`users` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `conversations_shop_one_id_foreign`
    FOREIGN KEY (`shop_one_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `conversations_shop_two_id_foreign`
    FOREIGN KEY (`shop_two_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`customers` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `credit_limit` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `current_debt` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `total_purchases` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `total_paid` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `notes` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `customers_shop_id_name_index` (`shop_id` ASC, `name` ASC) VISIBLE,
  INDEX `customers_phone_index` (`phone` ASC) VISIBLE,
  INDEX `customers_current_debt_index` (`current_debt` ASC) VISIBLE,
  CONSTRAINT `customers_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`sales` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `customer_id` CHAR(36) NULL DEFAULT NULL,
  `user_id` CHAR(36) NOT NULL,
  `sale_number` VARCHAR(255) NOT NULL,
  `subtotal` DECIMAL(15,2) NOT NULL,
  `tax_rate` DECIMAL(5,2) NOT NULL DEFAULT '0.00',
  `tax_amount` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `discount_amount` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `discount_percentage` DECIMAL(5,2) NOT NULL DEFAULT '0.00',
  `total_amount` DECIMAL(15,2) NOT NULL,
  `amount_paid` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `change_amount` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `debt_amount` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `profit_amount` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `status` ENUM('completed', 'pending', 'cancelled', 'refunded', 'partially_refunded') NOT NULL DEFAULT 'completed',
  `payment_status` ENUM('paid', 'partially_paid', 'pending', 'debt') NOT NULL DEFAULT 'paid',
  `notes` TEXT NULL DEFAULT NULL,
  `sale_date` TIMESTAMP NOT NULL,
  `converted_to_expense_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sales_sale_number_unique` (`sale_number` ASC) VISIBLE,
  INDEX `sales_customer_id_foreign` (`customer_id` ASC) VISIBLE,
  INDEX `sales_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `sales_shop_id_sale_date_index` (`shop_id` ASC, `sale_date` ASC) VISIBLE,
  INDEX `sales_shop_id_status_index` (`shop_id` ASC, `status` ASC) VISIBLE,
  INDEX `sales_shop_id_customer_id_index` (`shop_id` ASC, `customer_id` ASC) VISIBLE,
  INDEX `sales_shop_id_payment_status_index` (`shop_id` ASC, `payment_status` ASC) VISIBLE,
  INDEX `sales_sale_number_index` (`sale_number` ASC) VISIBLE,
  CONSTRAINT `sales_customer_id_foreign`
    FOREIGN KEY (`customer_id`)
    REFERENCES `maiduka25db`.`customers` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `sales_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `sales_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `maiduka25db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`expenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`expenses` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `sale_id` CHAR(36) NULL DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `category` VARCHAR(255) NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `expense_date` DATE NOT NULL,
  `payment_method` VARCHAR(255) NOT NULL,
  `receipt_number` VARCHAR(255) NULL DEFAULT NULL,
  `attachment_url` VARCHAR(255) NULL DEFAULT NULL,
  `recorded_by` CHAR(36) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `expenses_recorded_by_foreign` (`recorded_by` ASC) VISIBLE,
  INDEX `expenses_shop_id_expense_date_index` (`shop_id` ASC, `expense_date` ASC) VISIBLE,
  INDEX `expenses_shop_id_category_index` (`shop_id` ASC, `category` ASC) VISIBLE,
  INDEX `expenses_sale_id_foreign` (`sale_id` ASC) VISIBLE,
  CONSTRAINT `expenses_recorded_by_foreign`
    FOREIGN KEY (`recorded_by`)
    REFERENCES `maiduka25db`.`users` (`id`),
  CONSTRAINT `expenses_sale_id_foreign`
    FOREIGN KEY (`sale_id`)
    REFERENCES `maiduka25db`.`sales` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `expenses_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`products` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `category_id` CHAR(36) NOT NULL,
  `product_type` ENUM('physical', 'service', 'digital') NOT NULL DEFAULT 'physical',
  `service_duration` DECIMAL(8,2) NULL DEFAULT NULL COMMENT 'Duration in hours for service products',
  `hourly_rate` DECIMAL(15,2) NULL DEFAULT NULL COMMENT 'Hourly rate for service products',
  `product_name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `sku` VARCHAR(255) NULL DEFAULT NULL,
  `barcode` VARCHAR(255) NULL DEFAULT NULL,
  `purchase_quantity` INT NULL DEFAULT NULL,
  `total_amount_paid` DECIMAL(15,2) NULL DEFAULT NULL,
  `cost_per_unit` DECIMAL(15,2) NULL DEFAULT NULL,
  `unit_type` ENUM('box', 'carton', 'piece', 'pack', 'bottle', 'bag', 'sachet', 'kg', 'gram', 'liter', 'ml') NOT NULL,
  `break_down_count_per_unit` INT NULL DEFAULT NULL,
  `small_item_name` VARCHAR(255) NULL DEFAULT NULL,
  `sell_whole_units` TINYINT(1) NOT NULL DEFAULT '1',
  `price_per_unit` DECIMAL(15,2) NULL DEFAULT NULL,
  `sell_individual_items` TINYINT(1) NOT NULL DEFAULT '0',
  `price_per_item` DECIMAL(15,2) NULL DEFAULT NULL,
  `sell_in_bundles` TINYINT(1) NOT NULL DEFAULT '0',
  `current_stock` INT NULL DEFAULT NULL,
  `low_stock_threshold` INT NULL DEFAULT NULL,
  `track_inventory` TINYINT(1) NOT NULL DEFAULT '1',
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `products_sku_unique` (`sku` ASC) VISIBLE,
  UNIQUE INDEX `products_barcode_unique` (`barcode` ASC) VISIBLE,
  INDEX `products_category_id_foreign` (`category_id` ASC) VISIBLE,
  INDEX `products_shop_id_category_id_index` (`shop_id` ASC, `category_id` ASC) VISIBLE,
  INDEX `products_product_name_index` (`product_name` ASC) VISIBLE,
  INDEX `products_sku_index` (`sku` ASC) VISIBLE,
  INDEX `products_barcode_index` (`barcode` ASC) VISIBLE,
  INDEX `products_current_stock_low_stock_threshold_index` (`current_stock` ASC, `low_stock_threshold` ASC) VISIBLE,
  CONSTRAINT `products_category_id_foreign`
    FOREIGN KEY (`category_id`)
    REFERENCES `maiduka25db`.`categories` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `products_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`messages` (
  `id` CHAR(36) NOT NULL,
  `conversation_id` CHAR(36) NOT NULL,
  `sender_shop_id` CHAR(36) NOT NULL,
  `sender_user_id` CHAR(36) NOT NULL,
  `receiver_shop_id` CHAR(36) NOT NULL,
  `message` TEXT NULL DEFAULT NULL,
  `message_type` ENUM('text', 'image', 'video', 'audio', 'document', 'product', 'location') NOT NULL DEFAULT 'text',
  `attachments` JSON NULL DEFAULT NULL,
  `product_id` CHAR(36) NULL DEFAULT NULL,
  `location_lat` VARCHAR(255) NULL DEFAULT NULL,
  `location_lng` VARCHAR(255) NULL DEFAULT NULL,
  `location_name` VARCHAR(255) NULL DEFAULT NULL,
  `is_read` TINYINT(1) NOT NULL DEFAULT '0',
  `read_at` TIMESTAMP NULL DEFAULT NULL,
  `is_delivered` TINYINT(1) NOT NULL DEFAULT '0',
  `delivered_at` TIMESTAMP NULL DEFAULT NULL,
  `reply_to_message_id` CHAR(36) NULL DEFAULT NULL,
  `is_deleted_by_sender` TINYINT(1) NOT NULL DEFAULT '0',
  `is_deleted_by_receiver` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `messages_sender_user_id_foreign` (`sender_user_id` ASC) VISIBLE,
  INDEX `messages_product_id_foreign` (`product_id` ASC) VISIBLE,
  INDEX `messages_reply_to_message_id_foreign` (`reply_to_message_id` ASC) VISIBLE,
  INDEX `messages_conversation_id_created_at_index` (`conversation_id` ASC, `created_at` ASC) VISIBLE,
  INDEX `messages_receiver_shop_id_is_read_index` (`receiver_shop_id` ASC, `is_read` ASC) VISIBLE,
  INDEX `messages_sender_shop_id_index` (`sender_shop_id` ASC) VISIBLE,
  CONSTRAINT `messages_conversation_id_foreign`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `maiduka25db`.`conversations` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `messages_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `maiduka25db`.`products` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `messages_receiver_shop_id_foreign`
    FOREIGN KEY (`receiver_shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `messages_reply_to_message_id_foreign`
    FOREIGN KEY (`reply_to_message_id`)
    REFERENCES `maiduka25db`.`messages` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `messages_sender_shop_id_foreign`
    FOREIGN KEY (`sender_shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `messages_sender_user_id_foreign`
    FOREIGN KEY (`sender_user_id`)
    REFERENCES `maiduka25db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`message_reactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`message_reactions` (
  `id` CHAR(36) NOT NULL,
  `message_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `reaction` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `message_reactions_message_id_user_id_unique` (`message_id` ASC, `user_id` ASC) VISIBLE,
  INDEX `message_reactions_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `message_reactions_message_id_index` (`message_id` ASC) VISIBLE,
  CONSTRAINT `message_reactions_message_id_foreign`
    FOREIGN KEY (`message_id`)
    REFERENCES `maiduka25db`.`messages` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `message_reactions_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `maiduka25db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`purchase_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`purchase_orders` (
  `id` CHAR(36) NOT NULL,
  `buyer_shop_id` CHAR(36) NOT NULL,
  `seller_shop_id` CHAR(36) NOT NULL,
  `is_internal` TINYINT(1) NOT NULL DEFAULT '0',
  `reference_number` VARCHAR(255) NOT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'pending',
  `total_amount` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `total_paid` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `notes` TEXT NULL DEFAULT NULL,
  `approved_at` TIMESTAMP NULL DEFAULT NULL,
  `approved_by` CHAR(36) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `purchase_orders_reference_number_unique` (`reference_number` ASC) VISIBLE,
  INDEX `purchase_orders_buyer_shop_id_foreign` (`buyer_shop_id` ASC) VISIBLE,
  INDEX `purchase_orders_seller_shop_id_foreign` (`seller_shop_id` ASC) VISIBLE,
  INDEX `purchase_orders_approved_by_foreign` (`approved_by` ASC) VISIBLE,
  CONSTRAINT `purchase_orders_approved_by_foreign`
    FOREIGN KEY (`approved_by`)
    REFERENCES `maiduka25db`.`users` (`id`),
  CONSTRAINT `purchase_orders_buyer_shop_id_foreign`
    FOREIGN KEY (`buyer_shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`),
  CONSTRAINT `purchase_orders_seller_shop_id_foreign`
    FOREIGN KEY (`seller_shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`purchase_order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`purchase_order_items` (
  `id` CHAR(36) NOT NULL,
  `purchase_order_id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `quantity` INT NOT NULL,
  `unit_price` DECIMAL(15,2) NOT NULL,
  `total_price` DECIMAL(15,2) NOT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `purchase_order_items_purchase_order_id_foreign` (`purchase_order_id` ASC) VISIBLE,
  INDEX `purchase_order_items_product_id_foreign` (`product_id` ASC) VISIBLE,
  CONSTRAINT `purchase_order_items_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `maiduka25db`.`products` (`id`),
  CONSTRAINT `purchase_order_items_purchase_order_id_foreign`
    FOREIGN KEY (`purchase_order_id`)
    REFERENCES `maiduka25db`.`purchase_orders` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`purchase_payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`purchase_payments` (
  `id` CHAR(36) NOT NULL,
  `purchase_order_id` CHAR(36) NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `payment_method` VARCHAR(255) NOT NULL,
  `reference_number` VARCHAR(255) NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `recorded_by` CHAR(36) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `purchase_payments_purchase_order_id_foreign` (`purchase_order_id` ASC) VISIBLE,
  INDEX `purchase_payments_recorded_by_foreign` (`recorded_by` ASC) VISIBLE,
  CONSTRAINT `purchase_payments_purchase_order_id_foreign`
    FOREIGN KEY (`purchase_order_id`)
    REFERENCES `maiduka25db`.`purchase_orders` (`id`),
  CONSTRAINT `purchase_payments_recorded_by_foreign`
    FOREIGN KEY (`recorded_by`)
    REFERENCES `maiduka25db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`sale_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`sale_items` (
  `id` CHAR(36) NOT NULL,
  `sale_id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NULL DEFAULT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `product_sku` VARCHAR(255) NULL DEFAULT NULL,
  `quantity` DECIMAL(10,2) NOT NULL,
  `unit_type` VARCHAR(255) NULL DEFAULT NULL,
  `original_price` DECIMAL(15,2) NOT NULL,
  `selling_price` DECIMAL(15,2) NOT NULL,
  `cost_price` DECIMAL(15,2) NOT NULL,
  `discount_amount` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `discount_percentage` DECIMAL(5,2) NOT NULL DEFAULT '0.00',
  `tax_amount` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `subtotal` DECIMAL(15,2) NOT NULL,
  `total` DECIMAL(15,2) NOT NULL,
  `profit` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `sale_items_sale_id_index` (`sale_id` ASC) VISIBLE,
  INDEX `sale_items_product_id_index` (`product_id` ASC) VISIBLE,
  CONSTRAINT `sale_items_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `maiduka25db`.`products` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `sale_items_sale_id_foreign`
    FOREIGN KEY (`sale_id`)
    REFERENCES `maiduka25db`.`sales` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`sale_payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`sale_payments` (
  `id` CHAR(36) NOT NULL,
  `sale_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `payment_method` ENUM('cash', 'mobile_money', 'bank_transfer', 'credit', 'cheque') NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `reference_number` VARCHAR(255) NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `payment_date` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `sale_payments_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `sale_payments_sale_id_index` (`sale_id` ASC) VISIBLE,
  INDEX `sale_payments_payment_method_index` (`payment_method` ASC) VISIBLE,
  INDEX `sale_payments_payment_date_index` (`payment_date` ASC) VISIBLE,
  CONSTRAINT `sale_payments_sale_id_foreign`
    FOREIGN KEY (`sale_id`)
    REFERENCES `maiduka25db`.`sales` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `sale_payments_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `maiduka25db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`sale_refunds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`sale_refunds` (
  `id` CHAR(36) NOT NULL,
  `sale_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `reason` VARCHAR(255) NOT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `refund_date` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `sale_refunds_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `sale_refunds_sale_id_index` (`sale_id` ASC) VISIBLE,
  INDEX `sale_refunds_refund_date_index` (`refund_date` ASC) VISIBLE,
  CONSTRAINT `sale_refunds_sale_id_foreign`
    FOREIGN KEY (`sale_id`)
    REFERENCES `maiduka25db`.`sales` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `sale_refunds_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `maiduka25db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`savings_goals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`savings_goals` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `target_amount` DECIMAL(15,2) NOT NULL,
  `target_date` DATE NULL DEFAULT NULL,
  `current_amount` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `amount_withdrawn` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `progress_percentage` INT NOT NULL DEFAULT '0',
  `status` ENUM('active', 'completed', 'cancelled', 'paused') NOT NULL DEFAULT 'active',
  `completed_at` TIMESTAMP NULL DEFAULT NULL,
  `started_at` TIMESTAMP NULL DEFAULT NULL,
  `icon` VARCHAR(255) NULL DEFAULT NULL,
  `color` VARCHAR(255) NULL DEFAULT NULL,
  `priority` INT NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `savings_goals_shop_id_status_index` (`shop_id` ASC, `status` ASC) VISIBLE,
  CONSTRAINT `savings_goals_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`savings_transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`savings_transactions` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `savings_goal_id` CHAR(36) NULL DEFAULT NULL,
  `type` ENUM('deposit', 'withdrawal') NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `balance_before` DECIMAL(15,2) NOT NULL,
  `balance_after` DECIMAL(15,2) NOT NULL,
  `transaction_date` DATE NOT NULL,
  `daily_profit` DECIMAL(15,2) NULL DEFAULT NULL,
  `is_automatic` TINYINT(1) NOT NULL DEFAULT '1',
  `description` TEXT NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `processed_by` CHAR(36) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `savings_transactions_savings_goal_id_foreign` (`savings_goal_id` ASC) VISIBLE,
  INDEX `savings_transactions_processed_by_foreign` (`processed_by` ASC) VISIBLE,
  INDEX `savings_transactions_shop_id_type_index` (`shop_id` ASC, `type` ASC) VISIBLE,
  INDEX `savings_transactions_shop_id_transaction_date_index` (`shop_id` ASC, `transaction_date` ASC) VISIBLE,
  CONSTRAINT `savings_transactions_processed_by_foreign`
    FOREIGN KEY (`processed_by`)
    REFERENCES `maiduka25db`.`users` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `savings_transactions_savings_goal_id_foreign`
    FOREIGN KEY (`savings_goal_id`)
    REFERENCES `maiduka25db`.`savings_goals` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `savings_transactions_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`shop_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`shop_members` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `role` VARCHAR(255) NOT NULL,
  `permissions` JSON NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `shop_members_shop_id_user_id_unique` (`shop_id` ASC, `user_id` ASC) VISIBLE,
  INDEX `shop_members_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `shop_members_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `shop_members_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `maiduka25db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`shop_savings_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`shop_savings_settings` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `is_enabled` TINYINT(1) NOT NULL DEFAULT '0',
  `savings_type` ENUM('percentage', 'fixed_amount') NOT NULL DEFAULT 'percentage',
  `savings_percentage` DECIMAL(5,2) NULL DEFAULT NULL,
  `fixed_amount` DECIMAL(15,2) NULL DEFAULT NULL,
  `target_amount` DECIMAL(15,2) NULL DEFAULT NULL,
  `target_date` DATE NULL DEFAULT NULL,
  `withdrawal_frequency` ENUM('none', 'weekly', 'bi_weekly', 'monthly', 'quarterly', 'when_goal_reached') NOT NULL DEFAULT 'monthly',
  `auto_withdraw` TINYINT(1) NOT NULL DEFAULT '0',
  `minimum_withdrawal_amount` DECIMAL(15,2) NULL DEFAULT NULL,
  `current_balance` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `total_saved` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `total_withdrawn` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `last_savings_date` TIMESTAMP NULL DEFAULT NULL,
  `last_withdrawal_date` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `shop_savings_settings_shop_id_unique` (`shop_id` ASC) VISIBLE,
  CONSTRAINT `shop_savings_settings_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`shop_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`shop_settings` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `business_email` VARCHAR(255) NULL DEFAULT NULL,
  `business_website` VARCHAR(255) NULL DEFAULT NULL,
  `tax_id` VARCHAR(255) NULL DEFAULT NULL,
  `registration_number` VARCHAR(255) NULL DEFAULT NULL,
  `enable_sms_notifications` TINYINT(1) NOT NULL DEFAULT '1',
  `enable_email_notifications` TINYINT(1) NOT NULL DEFAULT '0',
  `notify_low_stock` TINYINT(1) NOT NULL DEFAULT '1',
  `low_stock_threshold` INT NOT NULL DEFAULT '10',
  `notify_daily_sales_summary` TINYINT(1) NOT NULL DEFAULT '0',
  `daily_summary_time` VARCHAR(255) NOT NULL DEFAULT '18:00',
  `auto_print_receipt` TINYINT(1) NOT NULL DEFAULT '0',
  `allow_credit_sales` TINYINT(1) NOT NULL DEFAULT '1',
  `credit_limit_days` INT NOT NULL DEFAULT '30',
  `require_customer_for_credit` TINYINT(1) NOT NULL DEFAULT '1',
  `allow_discounts` TINYINT(1) NOT NULL DEFAULT '1',
  `max_discount_percentage` DECIMAL(5,2) NOT NULL DEFAULT '20.00',
  `track_stock` TINYINT(1) NOT NULL DEFAULT '1',
  `allow_negative_stock` TINYINT(1) NOT NULL DEFAULT '0',
  `auto_deduct_stock_on_sale` TINYINT(1) NOT NULL DEFAULT '1',
  `stock_valuation_method` VARCHAR(255) NOT NULL DEFAULT 'fifo',
  `receipt_header` TEXT NULL DEFAULT NULL,
  `receipt_footer` TEXT NULL DEFAULT NULL,
  `show_shop_logo_on_receipt` TINYINT(1) NOT NULL DEFAULT '1',
  `show_tax_on_receipt` TINYINT(1) NOT NULL DEFAULT '0',
  `tax_percentage` DECIMAL(5,2) NOT NULL DEFAULT '0.00',
  `opening_time` VARCHAR(255) NOT NULL DEFAULT '08:00',
  `closing_time` VARCHAR(255) NOT NULL DEFAULT '20:00',
  `working_days` JSON NULL DEFAULT NULL,
  `language` VARCHAR(255) NOT NULL DEFAULT 'sw',
  `timezone` VARCHAR(255) NOT NULL DEFAULT 'Africa/Dar_es_Salaam',
  `date_format` VARCHAR(255) NOT NULL DEFAULT 'd/m/Y',
  `time_format` VARCHAR(255) NOT NULL DEFAULT 'H:i',
  `require_pin_for_refunds` TINYINT(1) NOT NULL DEFAULT '1',
  `require_pin_for_discounts` TINYINT(1) NOT NULL DEFAULT '0',
  `enable_two_factor_auth` TINYINT(1) NOT NULL DEFAULT '0',
  `auto_backup` TINYINT(1) NOT NULL DEFAULT '0',
  `backup_frequency` VARCHAR(255) NOT NULL DEFAULT 'weekly',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `shop_settings_shop_id_unique` (`shop_id` ASC) VISIBLE,
  CONSTRAINT `shop_settings_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`shop_suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`shop_suppliers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `shop_id` CHAR(36) NOT NULL,
  `supplier_id` CHAR(36) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `shop_suppliers_shop_id_supplier_id_unique` (`shop_id` ASC, `supplier_id` ASC) VISIBLE,
  INDEX `shop_suppliers_supplier_id_foreign` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `shop_suppliers_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `shop_suppliers_supplier_id_foreign`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`stock_adjustments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`stock_adjustments` (
  `id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `type` ENUM('damaged', 'expired', 'lost', 'theft', 'personal_use', 'donation', 'return_to_supplier', 'other', 'restock', 'adjustment') NOT NULL,
  `quantity` INT NOT NULL,
  `value_at_time` DECIMAL(15,2) NOT NULL,
  `previous_stock` INT NOT NULL,
  `new_stock` INT NOT NULL,
  `reason` VARCHAR(255) NOT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `stock_adjustments_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `stock_adjustments_product_id_type_index` (`product_id` ASC, `type` ASC) VISIBLE,
  INDEX `stock_adjustments_created_at_index` (`created_at` ASC) VISIBLE,
  INDEX `stock_adjustments_type_index` (`type` ASC) VISIBLE,
  CONSTRAINT `stock_adjustments_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `maiduka25db`.`products` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `stock_adjustments_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `maiduka25db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`stock_transfers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`stock_transfers` (
  `id` CHAR(36) NOT NULL,
  `purchase_order_id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `quantity` INT NOT NULL,
  `transferred_at` TIMESTAMP NOT NULL,
  `transferred_by` CHAR(36) NOT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `stock_transfers_purchase_order_id_foreign` (`purchase_order_id` ASC) VISIBLE,
  INDEX `stock_transfers_product_id_foreign` (`product_id` ASC) VISIBLE,
  INDEX `stock_transfers_transferred_by_foreign` (`transferred_by` ASC) VISIBLE,
  CONSTRAINT `stock_transfers_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `maiduka25db`.`products` (`id`),
  CONSTRAINT `stock_transfers_purchase_order_id_foreign`
    FOREIGN KEY (`purchase_order_id`)
    REFERENCES `maiduka25db`.`purchase_orders` (`id`),
  CONSTRAINT `stock_transfers_transferred_by_foreign`
    FOREIGN KEY (`transferred_by`)
    REFERENCES `maiduka25db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`subscriptions` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `plan` VARCHAR(255) NOT NULL DEFAULT 'free',
  `type` VARCHAR(255) NOT NULL DEFAULT 'offline',
  `status` VARCHAR(255) NOT NULL DEFAULT 'pending',
  `price` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `currency` VARCHAR(255) NOT NULL DEFAULT 'TZS',
  `starts_at` TIMESTAMP NULL DEFAULT NULL,
  `expires_at` TIMESTAMP NULL DEFAULT NULL,
  `auto_renew` TINYINT(1) NOT NULL DEFAULT '0',
  `payment_method` VARCHAR(255) NULL DEFAULT NULL,
  `transaction_reference` VARCHAR(255) NULL DEFAULT NULL,
  `features` JSON NULL DEFAULT NULL,
  `max_users` INT NULL DEFAULT NULL,
  `max_products` INT NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `cancelled_at` TIMESTAMP NULL DEFAULT NULL,
  `cancelled_reason` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `subscriptions_shop_id_status_index` (`shop_id` ASC, `status` ASC) VISIBLE,
  INDEX `subscriptions_expires_at_index` (`expires_at` ASC) VISIBLE,
  CONSTRAINT `subscriptions_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maiduka25db`.`typing_indicators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maiduka25db`.`typing_indicators` (
  `id` CHAR(36) NOT NULL,
  `conversation_id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `started_at` TIMESTAMP NOT NULL,
  `expires_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `typing_indicators_shop_id_foreign` (`shop_id` ASC) VISIBLE,
  INDEX `typing_indicators_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `typing_indicators_conversation_id_expires_at_index` (`conversation_id` ASC, `expires_at` ASC) VISIBLE,
  CONSTRAINT `typing_indicators_conversation_id_foreign`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `maiduka25db`.`conversations` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `typing_indicators_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `maiduka25db`.`shops` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `typing_indicators_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `maiduka25db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
